document.writeln("    <footer>");
document.writeln("        <div class=\'widewrapper footer\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <div class=\'col-md-4 footer-widget\'>");
document.writeln("                        <h3> <i class=\'fa fa-user\'></i>关于我们</h3>");
document.writeln("");
document.writeln("                        <p>我们是</p>");
document.writeln("                        <p>chocolate 论坛！</p>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <div class=\'col-md-4 footer-widget\'>");
document.writeln("                        <h3> <i class=\'fa fa-pencil\'></i>近日佳帖</h3>");
document.writeln("                        <ul class=\'clean-list\'>");
document.writeln("                            <li><a href=\'\'>C</a></li>");
document.writeln("                            <li><a href=\'\'>R</a></li>");
document.writeln("                            <li><a href=\'\'>Y</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    <div class=\'col-md-4 footer-widget\'>");
document.writeln("                        <h3> <i class=\'fa fa-envelope\'></i>联系我们</h3>");
document.writeln("");
document.writeln("                        <p>我们的负责人：夏某人</p>");
document.writeln("                        <p>我们的电话：138****4627</p>");
document.writeln("                        <div class=\'footer-widget-icon\'>");
document.writeln("                            <i class=\'fa fa-facebook\'></i><i class=\'fa fa-twitter\'></i><i class=\'fa fa-google\'></i>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'widewrapper copyright\'>");
document.writeln("            Copyright &copy; 2020.Company name All rights reserved.");
document.writeln("        </div>");
document.writeln("    </footer>");