document.writeln("    <header>");
document.writeln("");
document.writeln("        <div class=\'widewrapper masthead\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <a href=\'index.html\' id=\'logo\'>");
document.writeln("                    <div style=\'font-size: 70px; font-style: italic\'>Chocolate论坛</div>");
document.writeln("                </a>");
document.writeln("");
document.writeln("                <div id=\'mobile-nav-toggle\' class=\'pull-right\'>");
document.writeln("                    <a href=\'#\' data-toggle=\'collapse\' data-target=\'.clean-nav .navbar-collapse\'>");
document.writeln("                        <i class=\'fa fa-bars\'></i>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <nav class=\'pull-right clean-nav\'>");
document.writeln("                    <div class=\'collapse navbar-collapse\'>");
document.writeln("                        <ul class=\'nav nav-pills navbar-nav\'>");
document.writeln("");
document.writeln("                            <li>");
document.writeln("                                <a href=\'index.html\' onclick=\'login1()\'>主页</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'post.html\' onclick=\'login2()\'>发帖</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a id=\'user\' href=\'about.html\' onclick=\'login3()\'>登录/注册</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'widewrapper subheader\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'clean-breadcrumb\'>");
document.writeln("                    <a href=\'#\'> 论坛热点 </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'clean-searchbox\'>");
document.writeln("                    <form action=\'#\' method=\'get\' accept-charset=\'utf-8\'>");
document.writeln("");
document.writeln("                        <input id=\'searchbox\' type=\'text\' placeholder=\'请输入您的id\'>");
document.writeln("                            <input type=\'button\' class=\'searchbutton\' onclick=\'gethistory()\' id=\'btn\' value=\'帖子\'>");
document.writeln("                                <i class=\'fa fa-search\'></i><a href=\'search.html\'></a>");
document.writeln("                                <input type=\'button\' class=\'searchbutton\' onclick=\'gethistory2()\' id=\'btn2\' value=\'评论\'>");
document.writeln("                                    <i class=\'fa fa - search\'><a href=\'search2.html\'></a></i>");
document.writeln("                    </form>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");

